-- MySQL Script generated by MySQL Workbench
-- 05/23/17 18:05:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema nearshore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nearshore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nearshore` DEFAULT CHARACTER SET utf8 ;
USE `nearshore` ;

-- -----------------------------------------------------
-- Table `nearshore`.`cat_dominio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearshore`.`cat_dominio` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nearshore`.`cat_plataforma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearshore`.`cat_plataforma` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(2000) NULL DEFAULT NULL,
  `Comentarios` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nearshore`.`cat_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearshore`.`cat_proveedor` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nearshore`.`aplicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearshore`.`aplicacion` (
  `Csi_Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Id_Dominio` INT(11) NULL DEFAULT NULL,
  `Ptb_Id` VARCHAR(45) NULL DEFAULT NULL,
  `Descripcion_Corta` VARCHAR(200) NULL DEFAULT NULL,
  `Descripcion_Larga` VARCHAR(2000) NULL DEFAULT NULL,
  `Id_L1` INT(11) NULL DEFAULT NULL,
  `Id_L2` INT(11) NULL DEFAULT NULL,
  `Id_L3` INT(11) NULL DEFAULT NULL,
  `Id_Plat1` INT(11) NULL DEFAULT NULL,
  `Id_Plat2` INT(11) NULL DEFAULT NULL,
  `Id_Plat3` INT(11) NULL DEFAULT NULL,
  `Comentarios` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`Csi_Id`),
  INDEX `fk_CatDominio_Aplicacion_idx` (`Id_Dominio` ASC),
  INDEX `fk_CatProveedor_Aplicacion_idx` (`Id_L1` ASC),
  INDEX `fk_CatProveedor_Aplicacion_idx1` (`Id_L2` ASC),
  INDEX `fk_CatProveedor_Aplicacion_L3_idx` (`Id_L3` ASC),
  INDEX `fk_CatPlataforma_Aplicacion_Id_Plat1_idx` (`Id_Plat1` ASC),
  INDEX `fk_CatPlataforma_Aplicacion_Id_Plat2_idx` (`Id_Plat2` ASC),
  INDEX `fk_CatPlataforma_Aplicacion_Id_Plat3_idx` (`Id_Plat3` ASC),
  CONSTRAINT `fk_CAT_DOMINIO_APLICACION`
    FOREIGN KEY (`Id_Dominio`)
    REFERENCES `nearshore`.`cat_dominio` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PLATAFORMA_APLICACION_Id_Plat1`
    FOREIGN KEY (`Id_Plat1`)
    REFERENCES `nearshore`.`cat_plataforma` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PLATAFORMA_APLICACION_Id_Plat2`
    FOREIGN KEY (`Id_Plat2`)
    REFERENCES `nearshore`.`cat_plataforma` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PROVEEDOR_APICACION_Id_L1`
    FOREIGN KEY (`Id_L1`)
    REFERENCES `nearshore`.`cat_proveedor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PROVEEDOR_APICACION_Id_L2`
    FOREIGN KEY (`Id_L2`)
    REFERENCES `nearshore`.`cat_proveedor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PROVEEDOR_APICACION_Id_L3`
    FOREIGN KEY (`Id_L3`)
    REFERENCES `nearshore`.`cat_proveedor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PROVEEDOR_APICACION_Id_Plat3`
    FOREIGN KEY (`Id_Plat3`)
    REFERENCES `nearshore`.`cat_plataforma` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nearshore`.`cat_pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearshore`.`cat_pais` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nearshore`.`cat_ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearshore`.`cat_ciudad` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Id_Pais` INT(11) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_CatPais_CatCiudad_idx` (`Id_Pais` ASC),
  CONSTRAINT `fk_CAT_PAIS_CAT_CIUDAD`
    FOREIGN KEY (`Id_Pais`)
    REFERENCES `nearshore`.`cat_pais` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nearshore`.`cat_puesto_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearshore`.`cat_puesto_proveedor` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nearshore`.`recurso_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearshore`.`recurso_proveedor` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Id_Proveedor` INT(11) NOT NULL,
  `Clave_Empleado` INT(11) NOT NULL,
  `Apellido_Paterno` VARCHAR(45) NULL DEFAULT NULL,
  `Apellido_Materno` VARCHAR(45) NULL DEFAULT NULL,
  `Primer_Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Segundo_Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Id_Ciudad` INT(11) NULL DEFAULT NULL,
  `Movil_Personal` VARCHAR(10) NULL DEFAULT NULL,
  `Telefono_Particular` VARCHAR(10) NULL DEFAULT NULL,
  `Email_Personal` VARCHAR(60) NULL DEFAULT NULL,
  `Id_Puesto` INT(11) NULL DEFAULT NULL,
  `Id_Reporta_A` INT(11) NULL DEFAULT NULL,
  `Telefono_Proveedor` VARCHAR(10) NULL DEFAULT NULL,
  `Ext_Proveedor` VARCHAR(10) NULL DEFAULT NULL,
  `Email_Proveedor` VARCHAR(60) NULL DEFAULT NULL,
  `Soe_Id` VARCHAR(7) NULL DEFAULT NULL,
  `Ext_Citi` VARCHAR(10) NULL DEFAULT NULL,
  `Email_Citi` VARCHAR(60) NULL DEFAULT NULL,
  `Comentarios` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_CAT_PROVEEDOR_RECURSOS_PROVEEDOR_idx` (`Id_Proveedor` ASC),
  INDEX `fk_CAT_CIUDAD_RECURSOS_PROVEEDOR_idx` (`Id_Ciudad` ASC),
  INDEX `fk_CAT_PUESTO_PROVEEDOR_RECURSOS_PROVEEDOR_idx` (`Id_Puesto` ASC),
  UNIQUE INDEX `Clave_Empleado_UNIQUE` (`Clave_Empleado` ASC),
  CONSTRAINT `fk_CAT_CIUDAD_RECURSO_PROVEEDOR`
    FOREIGN KEY (`Id_Ciudad`)
    REFERENCES `nearshore`.`cat_ciudad` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PROVEEDOR_RECURSO_PROVEEDOR`
    FOREIGN KEY (`Id_Proveedor`)
    REFERENCES `nearshore`.`cat_proveedor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PUESTO_PROVEEDOR_RECURSO_PROVEEDOR`
    FOREIGN KEY (`Id_Puesto`)
    REFERENCES `nearshore`.`cat_puesto_proveedor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nearshore`.`aplicacion_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearshore`.`aplicacion_proveedor` (
  `Id_Aplicacion_Proveedor` INT(11) NOT NULL AUTO_INCREMENT,
  `Id_Proveedor` INT(11) NOT NULL,
  `Csi_Id` INT(11) NOT NULL,
  `L1_Primario` INT(11) NULL,
  `L1_Backup` INT(11) NULL DEFAULT NULL,
  `L2_Primario` INT(11) NULL DEFAULT NULL,
  `L2_Backup` INT(11) NULL DEFAULT NULL,
  `L3_Primario` INT(11) NULL DEFAULT NULL,
  `L3_Backup` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Aplicacion_Proveedor`, `Id_Proveedor`, `Csi_Id`),
  INDEX `fk_APLICACION_APLICACION_PROVEEDOR_idx` (`Csi_Id` ASC),
  INDEX `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_idx` (`L1_Primario` ASC),
  INDEX `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_1_idx` (`L1_Backup` ASC),
  INDEX `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_2_idx` (`L2_Primario` ASC),
  INDEX `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_3_idx` (`L2_Backup` ASC),
  INDEX `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_4_idx` (`L3_Primario` ASC),
  INDEX `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_5_idx` (`L3_Backup` ASC),
  CONSTRAINT `fk_APLICACION_APLICACION_PROVEEDOR`
    FOREIGN KEY (`Csi_Id`)
    REFERENCES `nearshore`.`aplicacion` (`Csi_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PROVEEDOR_APLICACION_PROVEEDOR`
    FOREIGN KEY (`Id_Proveedor`)
    REFERENCES `nearshore`.`cat_proveedor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR`
    FOREIGN KEY (`L1_Primario`)
    REFERENCES `nearshore`.`recurso_proveedor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_1`
    FOREIGN KEY (`L1_Backup`)
    REFERENCES `nearshore`.`recurso_proveedor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_2`
    FOREIGN KEY (`L2_Primario`)
    REFERENCES `nearshore`.`recurso_proveedor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_3`
    FOREIGN KEY (`L2_Backup`)
    REFERENCES `nearshore`.`recurso_proveedor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_4`
    FOREIGN KEY (`L3_Primario`)
    REFERENCES `nearshore`.`recurso_proveedor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECURSO_PROVEEDOR_APLICACION_PROVEEDOR_5`
    FOREIGN KEY (`L3_Backup`)
    REFERENCES `nearshore`.`recurso_proveedor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nearshore`.`cat_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearshore`.`cat_perfil` (
  `Id_Perfil` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Perfil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nearshore`.`cat_puestociti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearshore`.`cat_puestociti` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nearshore`.`recurso_citi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearshore`.`recurso_citi` (
  `Soe_Id` VARCHAR(7) NOT NULL,
  `Apellido_Paterno` VARCHAR(45) NULL DEFAULT NULL,
  `Apellido_Materno` VARCHAR(45) NULL DEFAULT NULL,
  `Primer_Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Segundo_Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Id_Dominio` INT(11) NULL DEFAULT NULL,
  `Id_Puesto` INT(11) NULL DEFAULT NULL,
  `Id_Ciudad` INT(11) NULL DEFAULT NULL,
  `Ext` VARCHAR(10) NULL DEFAULT NULL,
  `Movil` VARCHAR(10) NULL DEFAULT NULL,
  `Telefono` VARCHAR(10) NULL DEFAULT NULL,
  `Email` VARCHAR(60) NULL DEFAULT NULL,
  `Id_ReportaA` VARCHAR(7) NULL DEFAULT NULL,
  `Comentarios` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`Soe_Id`),
  INDEX `fk_CatDominio_RecursoCiti_Dominio_idx` (`Id_Dominio` ASC),
  INDEX `fk_CatpuestoCiti_IdPuesto_idx` (`Id_Puesto` ASC),
  INDEX `fk_CatCiudad_Id_Ciudad_idx` (`Id_Ciudad` ASC),
  INDEX `fk_RecursoCiti_RecursoCiti_idx` (`Id_ReportaA` ASC),
  CONSTRAINT `fk_CAT_CIUDAD_RECURSO_CITI`
    FOREIGN KEY (`Id_Ciudad`)
    REFERENCES `nearshore`.`cat_ciudad` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_DOMINIO_RECURSO_CITI`
    FOREIGN KEY (`Id_Dominio`)
    REFERENCES `nearshore`.`cat_dominio` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAT_PUESTOCITI_RECURSO_CITI`
    FOREIGN KEY (`Id_Puesto`)
    REFERENCES `nearshore`.`cat_puestociti` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECURSO_CITIi_RECURSO_CITI`
    FOREIGN KEY (`Id_ReportaA`)
    REFERENCES `nearshore`.`recurso_citi` (`Soe_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nearshore`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearshore`.`usuario` (
  `Id_Usuarios` INT(11) NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(60) NULL DEFAULT NULL,
  `Primer_Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Segundo_Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Apellido_Paterno` VARCHAR(45) NULL DEFAULT NULL,
  `ApellidoMaterno` VARCHAR(45) NULL DEFAULT NULL,
  `Clave` VARCHAR(45) NULL DEFAULT NULL,
  `Id_Perfil` INT(11) NULL DEFAULT NULL,
  `Activo` TINYINT(1) NULL DEFAULT NULL,
  `Dominios` VARCHAR(2000) NULL DEFAULT NULL,
  `Proveedores` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Usuarios`),
  INDEX `fk_CAT_PERFIL_USUARIO_idx` (`Id_Perfil` ASC),
  CONSTRAINT `fk_CAT_PERFIL_USUARIO`
    FOREIGN KEY (`Id_Perfil`)
    REFERENCES `nearshore`.`cat_perfil` (`Id_Perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nearshore`.`recursoCiti_aplicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearshore`.`recursoCiti_aplicacion` (
  `idrecursoCiti_aplicacion` INT NOT NULL AUTO_INCREMENT,
  `idAplicacion` INT NULL,
  `id_recurso_citi` INT NULL,
  PRIMARY KEY (`idrecursoCiti_aplicacion`),
  INDEX `idAplicacion_idx` (`idAplicacion` ASC),
  INDEX `idRecursoCiti_idx` (`id_recurso_citi` ASC),
  CONSTRAINT `idAplicacion`
    FOREIGN KEY (`idAplicacion`)
    REFERENCES `nearshore`.`aplicacion` (`Csi_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRecursoCiti`
    FOREIGN KEY (`id_recurso_citi`)
    REFERENCES `nearshore`.`recurso_citi` (`Id_Dominio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
