variables:
  redis:
    #host: localhost
    host: hostRedis
    port: 6379
    password:
  eureka:
    #host: localhost
    host: hostEureka
    port: 8761
      
info:
  component: zuul
server:
  port: 8080
spring:
  config:
    name: zuul
  application:
    name: zuul
  redis:
    host: ${variables.redis.host}
    port: ${variables.redis.port}
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true
    
   
zuul:
  routes:
    dashboardEureka:
      path: /eureka/**
      url: http://${variables.eureka.host}:${variables.eureka.port}/

    phpMyadmin:
      path: /phpMyadmin/**
      serviceId: phpMyadmin

    # Microservicio DB
    mcTDCdbMain:
      path: /mcTDCdbMain/**
      serviceId: mcTDCdbMain

    # Microservicio nearshore-catalogsms
    nearshore-catalogsms:
      path:  /catalogsms/**
      serviceId: nearshore-catalogsms

    # Microservicio nearshore-appsms
    nearshore-appsms:
      path:  /appsms/**
      serviceId: nearshore-appsms

    login:
      path:  /app/**
      serviceId: nearshore-appsms
      
    # Microservicio nearshore-employeesms
    nearshore-employeesms:
      path:  /employeesms/**
      serviceId: nearshore-employeesms
    mcapp:
      path: /mcapp/**
      serviceId: mcapp
 
logging:
  level:
    com.banamex.nearshore: DEBUG
 
 
       
#10 minutos en timeout de respuesta y 5 minutos para tratar de conectars
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000
ribbon:
  ConnectTimeout: 300000
  ReadTimeout: 600000