variables:
  eureka:
    #host: hostEureka
    host: localhost
    port: 8761
      
    
info:
  component: zuul server app
 
server:
  port: 8080
spring:
  config:
    name: zuul
  application:
    name: zuul
 
    
zuul:
  routes:
    dashboardEureka:
      path: /eureka/**
      url: http://${variables.eureka.host}:${variables.eureka.port}/
       
    app:
      path: /appTest/**
      serviceId: appTest  
      
    phpMyadmin:
      path: /phpMyadmin/**
      serviceId: phpMyadmin  
      
    nearshore:
      path: /nearshore/**
      serviceId: nearshore  
    
    dbMcMysql:
      path: /dbMcMysql/**
      serviceId: dbMcMysql  

    horacioTest:
      path: /home/**
      serviceId: horacioTest
     
    
eureka:
  client:
  
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
    

logging:
  level:
    banamex.nearshore: DEBUG

       
#10 minutos en timeout de respuesta y 5 minutos para tratar de conectars
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000
ribbon:
  ConnectTimeout: 300000
  ReadTimeout: 600000
  
  

